// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/admin/all-invoices": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Lấy tất cả hóa đơn (admin)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object"
                            }
                        }
                    }
                }
            }
        },
        "/api/admin/invoice-detail": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Lấy chi tiết hóa đơn (admin)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Invoice ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Loại hóa đơn",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/cart": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Lấy giỏ hàng",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object"
                            }
                        }
                    }
                }
            }
        },
        "/api/categories": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Lấy danh sách danh mục",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Category"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Thêm danh mục",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tên danh mục",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Trạng thái",
                        "name": "status",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Ảnh danh mục",
                        "name": "image",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/categories/{id}": {
            "put": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Sửa danh mục",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tên danh mục",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Trạng thái",
                        "name": "status",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Ảnh danh mục",
                        "name": "image",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Category"
                ],
                "summary": "Xóa danh mục",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/insurance_accident/create_accident": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Accident"
                ],
                "summary": "Tạo hóa đơn bảo hiểm tai nạn (kèm danh sách người tham gia)",
                "parameters": [
                    {
                        "description": "Invoice info",
                        "name": "invoice",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.AccidentInvoiceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.AccidentInvoiceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/insurance_accident/update_invoice_customer": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Accident"
                ],
                "summary": "Gán customer_id vào hóa đơn tai nạn",
                "parameters": [
                    {
                        "description": "Update info",
                        "name": "update",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/insurance_cancer/confirm_purchase": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CarOwner"
                ],
                "summary": "Xác nhận mua bảo hiểm xe ô tô, xe máy, ung thư, sức khỏe cá nhân",
                "parameters": [
                    {
                        "description": "Confirm info",
                        "name": "confirm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.ConfirmPurchaseInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/insurance_cancer/create_customer_registration": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "summary": "Đăng ký khách hàng",
                "parameters": [
                    {
                        "description": "Customer info",
                        "name": "customer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CustomerRegistration"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/insurance_cancer/create_insurance_participant_info": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cancer"
                ],
                "summary": "Lưu danh sách người tham gia bảo hiểm ung thư",
                "parameters": [
                    {
                        "description": "Danh sách người tham gia",
                        "name": "participant",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CancerParticipantRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.CancerParticipantResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/insurance_cancer/create_invoice": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MotorbikeOwnerCarOwner"
                ],
                "summary": "Tạo hóa đơn bảo hiểm xe máy  Tạo hóa đơn bảo hiểm xe ô tô, ung thư, sức khỏe cá nhân",
                "parameters": [
                    {
                        "description": "Invoice info",
                        "name": "invoice",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Invoice"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/insurance_car_owner/confirm_purchase": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CarOwner"
                ],
                "summary": "Xác nhận mua bảo hiểm xe ô tô, xe máy, ung thư, sức khỏe cá nhân",
                "parameters": [
                    {
                        "description": "Confirm info",
                        "name": "confirm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.ConfirmPurchaseInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/insurance_car_owner/create_car_insurance_form": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CarOwner"
                ],
                "summary": "Lưu thông tin bảo hiểm xe ô tô",
                "parameters": [
                    {
                        "description": "Car insurance form",
                        "name": "carInsuranceForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CarInsuranceForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/insurance_car_owner/create_customer_registration": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "summary": "Đăng ký khách hàng",
                "parameters": [
                    {
                        "description": "Customer info",
                        "name": "customer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CustomerRegistration"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/insurance_car_owner/create_invoice": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MotorbikeOwnerCarOwner"
                ],
                "summary": "Tạo hóa đơn bảo hiểm xe máy  Tạo hóa đơn bảo hiểm xe ô tô, ung thư, sức khỏe cá nhân",
                "parameters": [
                    {
                        "description": "Invoice info",
                        "name": "invoice",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Invoice"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/insurance_car_owner/create_vehicle_insurance_form": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CarOwnerVehicle"
                ],
                "summary": "Lưu bảo hiểm vật chất xe ô tô",
                "parameters": [
                    {
                        "description": "Vehicle insurance form",
                        "name": "vehicleInsuranceForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/insurance_home/create_customer_registration": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "summary": "Đăng ký khách hàng",
                "parameters": [
                    {
                        "description": "Customer info",
                        "name": "customer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CustomerRegistration"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/insurance_home/create_home_invoice": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Home"
                ],
                "summary": "Tạo hóa đơn bảo hiểm nhà",
                "parameters": [
                    {
                        "description": "Invoice info",
                        "name": "invoice",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Invoice"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/insurance_home/update_invoice_customer": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Home"
                ],
                "summary": "Gán customer_id vào hóa đơn nhà",
                "parameters": [
                    {
                        "description": "Update info",
                        "name": "update",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/insurance_motorbike_owner/confirm_purchase": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CarOwner"
                ],
                "summary": "Xác nhận mua bảo hiểm xe ô tô, xe máy, ung thư, sức khỏe cá nhân",
                "parameters": [
                    {
                        "description": "Confirm info",
                        "name": "confirm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.ConfirmPurchaseInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/insurance_motorbike_owner/create_customer_registration": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "summary": "Đăng ký khách hàng",
                "parameters": [
                    {
                        "description": "Customer info",
                        "name": "customer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CustomerRegistration"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/insurance_motorbike_owner/create_invoice": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MotorbikeOwnerCarOwner"
                ],
                "summary": "Tạo hóa đơn bảo hiểm xe máy  Tạo hóa đơn bảo hiểm xe ô tô, ung thư, sức khỏe cá nhân",
                "parameters": [
                    {
                        "description": "Invoice info",
                        "name": "invoice",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Invoice"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/insurance_motorbike_owner/create_motorbike_insurance_form": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MotorbikeOwner"
                ],
                "summary": "Lưu bảo hiểm xe máy",
                "parameters": [
                    {
                        "description": "Motorbike insurance form",
                        "name": "motorbikeInsuranceForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.MotorbikeInsuranceForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/insurance_personal/confirm_purchase": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CarOwner"
                ],
                "summary": "Xác nhận mua bảo hiểm xe ô tô, xe máy, ung thư, sức khỏe cá nhân",
                "parameters": [
                    {
                        "description": "Confirm info",
                        "name": "confirm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.ConfirmPurchaseInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/insurance_personal/create_customer_registration": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "summary": "Đăng ký khách hàng",
                "parameters": [
                    {
                        "description": "Customer info",
                        "name": "customer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CustomerRegistration"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/insurance_personal/create_invoice": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MotorbikeOwnerCarOwner"
                ],
                "summary": "Tạo hóa đơn bảo hiểm xe máy  Tạo hóa đơn bảo hiểm xe ô tô, ung thư, sức khỏe cá nhân",
                "parameters": [
                    {
                        "description": "Invoice info",
                        "name": "invoice",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Invoice"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/insurance_personal/create_personal_insurance_form": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Personal"
                ],
                "summary": "Lưu bảo hiểm sức khỏe cá nhân",
                "parameters": [
                    {
                        "description": "Personal insurance form",
                        "name": "personalInsuranceForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PersonalInsuranceForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/insurance_travel/create_customer_registration": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "summary": "Đăng ký khách hàng",
                "parameters": [
                    {
                        "description": "Customer info",
                        "name": "customer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CustomerRegistration"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/insurance_travel/create_travel_invoice": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Travel"
                ],
                "summary": "Tạo hóa đơn bảo hiểm du lịch (kèm danh sách người tham gia)",
                "parameters": [
                    {
                        "description": "Invoice info",
                        "name": "invoice",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.TravelInvoiceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.TravelInvoiceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/insurance_travel/update_invoice_customer": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Travel"
                ],
                "summary": "Gán customer_id vào hóa đơn du lịch",
                "parameters": [
                    {
                        "description": "Update info",
                        "name": "update",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/invoice/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Invoice"
                ],
                "summary": "Lấy thông tin hóa đơn",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Invoice ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/posts": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "Thêm bài viết",
                "parameters": [
                    {
                        "description": "Post info",
                        "name": "post",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Post"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Post"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/posts/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "Sửa bài viết",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Post ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Post info",
                        "name": "post",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Post"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Post"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Post"
                ],
                "summary": "Xóa bài viết",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Post ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/products": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "Lấy danh sách sản phẩm",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Product"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "Thêm sản phẩm",
                "parameters": [
                    {
                        "description": "Product info",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Product"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/products/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "Sửa sản phẩm",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Product info",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Product"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Product"
                ],
                "summary": "Xóa sản phẩm",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Đăng nhập",
                "parameters": [
                    {
                        "description": "Login info",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Đăng ký tài khoản",
                "parameters": [
                    {
                        "description": "User info",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.AccidentInvoiceRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "contract_type": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "customer_id": {
                    "description": "Cho phép NULL",
                    "type": "integer"
                },
                "deleted_at": {
                    "type": "string"
                },
                "form_id": {
                    "description": "Có thể NULL",
                    "type": "integer"
                },
                "insurance_amount": {
                    "type": "number"
                },
                "insurance_end": {
                    "type": "string"
                },
                "insurance_package": {
                    "type": "string"
                },
                "insurance_quantity": {
                    "type": "integer"
                },
                "insurance_start": {
                    "type": "string"
                },
                "invoiceID": {
                    "type": "integer"
                },
                "participants": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Participant"
                    }
                },
                "product_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "description": "Cho phép NULL nếu không đăng nhập",
                    "type": "integer"
                }
            }
        },
        "handlers.AccidentInvoiceResponse": {
            "type": "object",
            "properties": {
                "invoice": {
                    "$ref": "#/definitions/models.Invoice"
                },
                "participants": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Participant"
                    }
                }
            }
        },
        "handlers.CancerParticipantRequest": {
            "type": "object",
            "properties": {
                "form_id": {
                    "type": "integer"
                },
                "participants": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.InsuranceParticipantInfo"
                    }
                }
            }
        },
        "handlers.CancerParticipantResponse": {
            "type": "object",
            "properties": {
                "form_id": {
                    "type": "integer"
                },
                "participants": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.InsuranceParticipantInfo"
                    }
                }
            }
        },
        "handlers.ConfirmPurchaseInput": {
            "type": "object",
            "properties": {
                "customer_id": {
                    "type": "integer"
                },
                "form_id": {
                    "type": "integer"
                },
                "invoice_id": {
                    "type": "integer"
                }
            }
        },
        "handlers.TravelInvoiceRequest": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "customer_id": {
                    "description": "cho phép NULL",
                    "type": "integer"
                },
                "deleted_at": {
                    "type": "string"
                },
                "departure_date": {
                    "type": "string"
                },
                "departure_location": {
                    "type": "string"
                },
                "destination": {
                    "type": "string"
                },
                "form_id": {
                    "description": "Cho phép NULL",
                    "type": "integer"
                },
                "group_size": {
                    "type": "integer"
                },
                "insurance_package": {
                    "type": "string"
                },
                "insurance_program": {
                    "type": "string"
                },
                "invoice_id": {
                    "type": "integer"
                },
                "note": {
                    "description": "Trường mới, ví dụ ghi chú",
                    "type": "string"
                },
                "participants": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.TravelParticipant"
                    }
                },
                "product_id": {
                    "type": "integer"
                },
                "return_date": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "total_amount": {
                    "description": "Đã cho phép nhập số",
                    "type": "number"
                },
                "total_duration": {
                    "description": "vẫn để gorm:\"-\" nếu là GENERATED",
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "handlers.TravelInvoiceResponse": {
            "type": "object",
            "properties": {
                "invoice": {
                    "$ref": "#/definitions/models.TravelInsuranceInvoice"
                },
                "participants": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.TravelParticipant"
                    }
                }
            }
        },
        "models.CarInsuranceForm": {
            "type": "object",
            "properties": {
                "car_form_id": {
                    "type": "integer"
                },
                "chassis_number": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "engine_number": {
                    "type": "string"
                },
                "form_id": {
                    "type": "integer"
                },
                "identity_number": {
                    "type": "string"
                },
                "insurance_amount": {
                    "type": "number"
                },
                "insurance_duration": {
                    "type": "integer"
                },
                "insurance_fee": {
                    "type": "number"
                },
                "insurance_start": {
                    "type": "string"
                },
                "license_plate": {
                    "type": "string"
                },
                "license_plate_status": {
                    "type": "string"
                },
                "load_capacity": {
                    "type": "number"
                },
                "owner_name": {
                    "type": "string"
                },
                "participant_count": {
                    "type": "integer"
                },
                "registration_address": {
                    "type": "string"
                },
                "seat_count": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "usage_purpose": {
                    "type": "string"
                },
                "user_type": {
                    "type": "string"
                },
                "vehicle_type": {
                    "type": "string"
                }
            }
        },
        "models.Category": {
            "type": "object",
            "properties": {
                "category_id": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "qty_product": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.CustomerRegistration": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "customer_id": {
                    "type": "integer"
                },
                "customer_type": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "identity_number": {
                    "type": "string"
                },
                "invoice_request": {
                    "type": "boolean"
                },
                "notes": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.InsuranceParticipantInfo": {
            "type": "object",
            "properties": {
                "birth_date": {
                    "type": "string"
                },
                "cmnd_img": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "customer_id": {
                    "description": "cho phép NULL",
                    "type": "integer"
                },
                "form_id": {
                    "type": "integer"
                },
                "full_name": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "had_stroke": {
                    "type": "boolean"
                },
                "has_cancer": {
                    "type": "boolean"
                },
                "identity_number": {
                    "type": "string"
                },
                "insurance_duration": {
                    "type": "integer"
                },
                "main_benefit": {
                    "type": "string"
                },
                "participant_id": {
                    "type": "integer"
                },
                "premium_fee": {
                    "type": "number"
                },
                "stage_four_disease": {
                    "type": "boolean"
                },
                "stroke_additional_benefit": {
                    "type": "boolean"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.Invoice": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "contract_type": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "customer_id": {
                    "description": "Cho phép NULL",
                    "type": "integer"
                },
                "deleted_at": {
                    "type": "string"
                },
                "form_id": {
                    "description": "Có thể NULL",
                    "type": "integer"
                },
                "insurance_amount": {
                    "type": "number"
                },
                "insurance_end": {
                    "type": "string"
                },
                "insurance_package": {
                    "type": "string"
                },
                "insurance_quantity": {
                    "type": "integer"
                },
                "insurance_start": {
                    "type": "string"
                },
                "invoiceID": {
                    "type": "integer"
                },
                "product_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "description": "Cho phép NULL nếu không đăng nhập",
                    "type": "integer"
                }
            }
        },
        "models.MotorbikeInsuranceForm": {
            "type": "object",
            "properties": {
                "accident_coverage": {
                    "type": "number"
                },
                "chassis_number": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "engine_capacity": {
                    "description": "Cho phép null",
                    "type": "number"
                },
                "engine_capacity_type": {
                    "description": "\"duoi_50cc\" hoặc \"tren_50cc\"",
                    "type": "string"
                },
                "engine_number": {
                    "type": "string"
                },
                "form_id": {
                    "type": "integer"
                },
                "insurance_duration": {
                    "type": "integer"
                },
                "insurance_fee": {
                    "type": "number"
                },
                "insurance_start": {
                    "type": "string"
                },
                "license_plate": {
                    "type": "string"
                },
                "license_plate_status": {
                    "type": "boolean"
                },
                "motorbike_form_id": {
                    "type": "integer"
                },
                "owner_name": {
                    "type": "string"
                },
                "registration_address": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "vehicle_type": {
                    "type": "string"
                }
            }
        },
        "models.Participant": {
            "type": "object",
            "properties": {
                "birth_date": {
                    "type": "string"
                },
                "cmnd_img": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "identity_number": {
                    "type": "string"
                },
                "invoice_id": {
                    "type": "integer"
                },
                "participant_id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.PersonalInsuranceForm": {
            "type": "object",
            "properties": {
                "birth_date": {
                    "type": "string"
                },
                "cmnd_img": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "dental_extension": {
                    "type": "boolean"
                },
                "form_id": {
                    "description": "Cho phép NULL",
                    "type": "integer"
                },
                "full_name": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "identity_number": {
                    "type": "string"
                },
                "insurance_duration": {
                    "type": "integer"
                },
                "insurance_fee": {
                    "type": "number"
                },
                "insurance_program": {
                    "type": "string"
                },
                "insurance_start": {
                    "type": "string"
                },
                "maternity_extension": {
                    "type": "boolean"
                },
                "personal_form_id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.Post": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "category_id": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "post_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "views": {
                    "type": "integer"
                }
            }
        },
        "models.Product": {
            "type": "object",
            "properties": {
                "category_id": {
                    "type": "integer"
                },
                "claimGuidelines": {
                    "description": "Hướng dẫn bồi thường",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "formRules": {
                    "description": "Quy tắc biểu mẫu",
                    "type": "string"
                },
                "generalInfo": {
                    "description": "Thông tin chung",
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "insuranceBenefits": {
                    "description": "Bảng quyền lợi bảo hiểm",
                    "type": "string"
                },
                "insuranceFee": {
                    "description": "Biểu phí bảo hiểm",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "product_id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                },
                "sale_price": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.TravelInsuranceInvoice": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "customer_id": {
                    "description": "cho phép NULL",
                    "type": "integer"
                },
                "deleted_at": {
                    "type": "string"
                },
                "departure_date": {
                    "type": "string"
                },
                "departure_location": {
                    "type": "string"
                },
                "destination": {
                    "type": "string"
                },
                "form_id": {
                    "description": "Cho phép NULL",
                    "type": "integer"
                },
                "group_size": {
                    "type": "integer"
                },
                "insurance_package": {
                    "type": "string"
                },
                "insurance_program": {
                    "type": "string"
                },
                "invoice_id": {
                    "type": "integer"
                },
                "note": {
                    "description": "Trường mới, ví dụ ghi chú",
                    "type": "string"
                },
                "product_id": {
                    "type": "integer"
                },
                "return_date": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "total_amount": {
                    "description": "Đã cho phép nhập số",
                    "type": "number"
                },
                "total_duration": {
                    "description": "vẫn để gorm:\"-\" nếu là GENERATED",
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.TravelParticipant": {
            "type": "object",
            "properties": {
                "birth_date": {
                    "type": "string"
                },
                "cmnd_img": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "identity_number": {
                    "type": "string"
                },
                "invoice_id": {
                    "description": "liên kết với TravelInsuranceInvoice",
                    "type": "integer"
                },
                "participant_id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "accountType": {
                    "type": "string"
                },
                "citizenID": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "dateOfBirth": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "houseNumber": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastName": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "province": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "subDistrict": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:5000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "BIC Insurance API",
	Description:      "API cho hệ thống bảo hiểm",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
